title: Ana Gomez # your name (or website title) here
logo: "/images/fotobn.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Engineer. Programmer. Positive Discipline Educator. Image Public Consultant. 
  <br><br>
  Energetic, enthusiastic, self-motivated and passionate about tech, children and education. 
  <br><br>
  <a href="https://www.linkedin.com/in/ana-gomez-mayen-b70539167/">View My LinkedIn Profile</a>
  <br>
  <a href="https://anagomezmayen.github.io/online-cv/">Resume</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
